services:
  docsify:
    user: 1000:1000
    build: ./docker/docsify
    container_name: docsify
    ports:
      - "10000:10000"
      - "35729:35729"
    volumes:
        - ./docs:/site
    working_dir: /site
    command: docsify serve . -p 10000 --livereload-port 35729

